env:
  browser: true
  es2020: true
  node: true
  mocha: true
extends:
  - standard
  - plugin:yml/standard
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  array-callback-return: off
  yml/plain-scalar: off
